#!/bin/bash
set -euo pipefail

DISK=${1:?Pass the disk as argument}

if mount | grep "$DISK" > /dev/null; then
    echo "Disk is already mounted"
    exit 1
fi

qemu-system-x86_64 \
  -enable-kvm \
  -hda $DISK \
  -netdev user,id=n0 -device rtl8139,netdev=n0 \
  -std-vga -full-screen\
  -m 16384
