#!/bin/bash

set -euo pipefail

ROOT=$(dirname "$(readlink -f "$0")")
TEST=${1:?First argument should be a test file}
TEST_NAME=$(basename "$TEST")
FOLDER=$(mktemp -d)

trap "rm -fr $FOLDER; exit" EXIT

cd "$ROOT"/..
cat "$TEST" | cargo run
cd "$ROOT"
