[package]
name = "blockchain"
version = "0.1.0"
authors = ["Agustin Chiappe Berrini <jnieve@gmail.com>"]

[dependencies]
rust-crypto = "^0.2"
failure = "0.1.3"
futures = "0.1.21"
hyper = "0.14.12"
serde = "1.0"
serde_derive = "1.0"
serde_json="1.0.32"
