#!/bin/bash

set -euo pipefail

ROOT=$(dirname "$(readlink -f "$0")")
TEST=${1:?First argument should be a test file}
TEST_NAME=$(basename "$TEST")
FOLDER=$(mktemp -d)

#trap "rm -fr $FOLDER; exit" EXIT

cd "$ROOT"/..
set +e
cabal --verbose=0 run "$TEST" >"$FOLDER"/"$TEST_NAME".out 2>"$FOLDER"/"$TEST_NAME".err
set -e
cd "$ROOT"

set +e
cat "$FOLDER"/"$TEST_NAME".out | grep -v -e "^ignoring" > "$FOLDER"/"$TEST_NAME".2.out
set -e

diff -N "$FOLDER"/"$TEST_NAME".2.out ./"$TEST_NAME".out
diff -N "$FOLDER"/"$TEST_NAME".err ./"$TEST_NAME".err